spring:
  application:
    name: gather_info
  datasource:
    driver-class-name:  org.postgresql.Driver
    url:  jdbc:postgresql://127.0.0.1:33133/gather_info
    username: gather_info
    password: Wang1980
  jpa:
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation:  true
        temp:
            use_jdbc_metadata_defaults: false
            
            

logging:
  level:
    root: INFO

          
          